### ISSUE TITLE
Aptly service doesn't start

### ISSUE THREAD

**Issue by rhoml** [tubemogul/puppet-aptly#21]
aptly-api starts just fine, but aptly webserver doesn't

**Comment by aerostitch** [comment]
Hi @rhoml ,

What OS are you on?
Did you publish anything already? If you don't have anything published, aptly server will serve nothing so will shutdown itself. That's the internal behavior of aptly.

Thanks
Joseph

**Comment by aerostitch** [comment]
Interesting. Thanks for the report.
Which version of the module do you use?
I'll try to reproduce the issue asap.

**Comment by rhoml** [comment]
mod 'TubeMogul-aptly', '2.1.0'

**Comment by rhoml** [comment]
So it was an aptly error apparently, just mirrored a debian repository and now aptly starts properly. He didn't just liked that I had my own custom packages apparently on the init

**Comment by rhoml** [comment]
Actually no, still doesn't work, aptly just dies after restart

**Comment by aerostitch** [comment]
Hi @rhoml ,

When you start aptly manually (and that it doesn't die), do you start it as root or as the aptly user?
When you launched the aptly commands to create the repository and publish it, did you run them as root?
Can you verify that the aptly user has the right to read and write on all the files of the `/data` directory?

Thanks
Joseph

**Comment by dhoppe** [comment]
I think the user _aptly_ does not have the permissions to bind a service to a port lower than 1024. Maybe we should stick to the default of 8080 and if necessary a user can use Apache2 or Nginx as reverse proxy. 

@rhoml What happens, if you override the port to 8080?

**Comment by rhoml** [comment]
I can confirm that this is related to the priviledged port and to #30 thanks for the help guys 👍
