### ISSUE TITLE
Use action show instead of list

### ISSUE THREAD

**Issue by dhoppe** [tubemogul/puppet-aptly#32]
For example the command `aptly publish -raw=true list` contains the distribution, not the name. Please rewrite all the `cli.rb` to use `aptly publish show resource[:name]` instead or you will get error messages like: 

```
Error: Execution of 'aptly  publish repo dhoppe' returned 1: ERROR: prefix/distribution already used by another published repo: ./jessie [] publishes {main: [dhoppe]}
```

This happens, because the exists? function does not recognize the already published repository.

**Comment by aerostitch** [comment]
The publish module is broken. There's been some work started in #19 . I'll take that one back when I have a chance to.

**Comment by dhoppe** [comment]
I just figured out that the publish command does not provide a show option.
