### ISSUE TITLE
Fix Travis CI configuration

### ISSUE THREAD

**Issue by dhoppe** [tubemogul/puppet-aptly#33]
Please fix Travis CI configuration. At the moment your matrix of used Ruby and Puppet versions is far to big and takes a lot of time to check. 

If you need an example, please take a look at following links:

https://github.com/voxpupuli/modulesync
https://github.com/voxpupuli/modulesync_config
https://travis-ci.org/voxpupuli/puppet-hiera

**Comment by aerostitch** [comment]
Changed in #34
